name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_timeout_ms: 900000
          language: ja-JP
          summarize: |
            最終的な回答を `markdown` フォーマットで以下の内容で書いてください:
            - 高レベルの要約（特定のファイルではなく、全体的な変更点についてのコメント日本語200文字以内)
            - ファイルとその要約のtableを書くこと
            - 同じような変更点のあるファイルをスペースを節約するために、同じような変更を持つファイルを1つの行にまとめてよい
            この要約は、GitHub の PullRequest にコメントとして追加されるので、追加コメントは避けること